---
- name: Désinstaller Docker de la machine locale
  hosts: localhost
  become: yes
  tasks:
    - name: Arrêter le service Docker
      service:
        name: docker
        state: stopped
      ignore_errors: yes

    - name: Supprimer les packages Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - docker-buildx-plugin
        state: absent
        purge: yes

    - name: Supprimer le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        state: absent

    - name: Supprimer la clé GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: absent

    - name: Retirer l'utilisateur du groupe docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        state: absent
      ignore_errors: yes

    - name: Nettoyer les dépendances inutiles
      apt:
        autoremove: yes
        autoclean: yes

    - name: Afficher message de fin
      debug:
        msg: "Docker a été désinstallé. Vous devrez peut-être redémarrer pour finaliser la suppression."
